# Generated by Django 5.1.4 on 2025-01-25 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('capacidad', models.IntegerField()),
                ('contenido', models.IntegerField()),
                ('vencimiento_filtro', models.DateField()),
                ('vencimiento_certificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloHelicoptero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=10)),
                ('capacidad_modelo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('matricula', models.CharField(max_length=6)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='fuel.modelohelicoptero')),
            ],
        ),
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('litros_cargados', models.IntegerField()),
                ('motivo', models.CharField(max_length=100)),
                ('despachador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emite_vale', to=settings.AUTH_USER_MODEL)),
                ('matricula_aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel.aeronave')),
                ('patente_camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel.camion')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibe_vale', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
